### ISSUE TITLE
conjugateTranspose produces _Xout_of_range("invalid vector subscript")

### ISSUE THREAD

**Issue by danielmpla** [cda-tum/mqt-misim#15]
Hi,

currently I'm trying out MiSiM. I've found the function `conjugateTranspose` and wanted to use it. However, I'm not sure, if it is intentended to be used by the enduser. And I'm not sure if I'm using C++ correct, since I haven't used it for 10 years.

Here is my code snippet:
```
using namespace dd;

void conjugateTransposeTest() {
    std::vector<std::size_t> lines{ 3 };
    unsigned int             numLines = 1U;

    auto dd = std::make_unique<MDDPackage>(numLines, lines); // Create new package instance capable of handling 2 qutrits
    auto zero_state = dd->makeZeroState(numLines);           // zero_state = |0>

    auto h_on_qutrit_0 = dd->makeGateDD<TritMatrix>(H3(), numLines, 0);

    auto psi = dd->multiply(h_on_qutrit_0, zero_state);
    psi = dd->multiply(dd->conjugateTranspose(h_on_qutrit_0), psi);

    dd->printVector(psi);
}
```

It produces the error:
```
[[noreturn]] static void _Xrange() {
    _Xout_of_range("invalid vector subscript");
}
```
at https://github.com/cda-tum/MiSiM/blob/db238f2ca4f0cdaaf37d50b3de1d593b679a500b/include/dd/MDDPackage.hpp#L1809

**Comment by KevinMTO** [comment]
Hi Daniel, thanks for the notification! I fixed the bug and pushed a pull request! Soon you will be able to the use the functionality as you intended :)

**Comment by burgholzer** [comment]
#16 is in 🎉
